services:
  - type: web
    name: aerotwin-backend
    env: node
    buildCommand: "bash build.sh"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
